### ISSUE TITLE
WPILib build uses different OpenCV than local build

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/WPILibPi#11]
Because of robotpy-cscore, and the need to build both python and java versions of opencv, we build our own opencv for the image.  However, since we use gradle to build allwpilib instead of cmake, the wpilib opencv build is used instead when compiling/linking.  This should not be an issue with identical versions, but poses a risk for upgrades.  The easiest solution is probably to switch to the cmake build of allwpilib.

**Comment by ThadHouse** [comment]
For sure. At that point, you could then use cmakes find_packafe utilities as a user to build if you wanted to.
