### ISSUE TITLE
Missing C++ include files

### ISSUE THREAD

**Issue by markkassab** [wpilibsuite/WPILibPi#196]
When including Timer.h from /usr/local/frc/include/frc, Timer.h attempts to #include frc2/Timer.h, but /usr/local/frc/include/frc2 is missing.
If frc2 is copied into place from /usr/src/allwpilib/wpilibc/src/main/native/include/frc2, then it includes units/time.h which is missing as well.

**Comment by AustinShalit** [comment]
@markkassab sorry about the delay here. Can you describe your setup and what you are trying to do?
