### ISSUE TITLE
Unable to enable wireless for raspbian

### ISSUE THREAD

**Issue by paul-foster** [wpilibsuite/WPILibPi#202]
I can't seem to re-enable the wireless. I started by going to raspi-config but there is no device recognized. I thought the device would simply be disabled, but it appears as if it doesn't even exist. How was the wifi removed to provide an FRC legal device?

**Comment by Daltz333** [comment]
I believe the actual package that allows wifi is not installed. You'd have to rebuild the image or ethernet in and install this package.

**Comment by PeterJohnson** [comment]
The kernel driver is blacklisted.  You can unblacklist it by removing `/etc/modprobe.d/raspi-blacklist.conf`

**Comment by paul-foster** [comment]
Thank you. raspi-config now shows the option to set the SSID
