### ISSUE TITLE
Release for 2022?

### ISSUE THREAD

**Issue by etiennebeaulac** [wpilibsuite/WPILibPi#220]
Hi! I have seen the commit #216 by @PeterJohnson, but I cannot find it on the Releases page. Am I missing something? Thanks!

**Comment by PeterJohnson** [comment]
I didn't get it tagged yet, will upgrade to 2022.4.1 and release after that.  Note there's not really a reason to upgrade, the 2021 version will work just fine.

**Comment by etiennebeaulac** [comment]
Awesome, thanks! We developed our vision code with OpenCV 4, but we ran into compatibility issues today with OpenCV 3. I saw that the 2022 image uses v4, that's why I tried to find it.

**Comment by PeterJohnson** [comment]
2022.1.1 has been released.

**Comment by etiennebeaulac** [comment]
Thank you!
