### ISSUE TITLE
did the 2022 update change the romi's motor channels?

### ISSUE THREAD

**Issue by SammyPants37** [wpilibsuite/WPILibPi#222]
I just updated the romi image to 2022 and now the romi won't drive is this because of the update or some other issue on my end

**Comment by jpokornyiii** [comment]
Can you confirm you can reach the romi via the webapi? Try http://wpilibpi.local or http://10.0.0.2. Re-imaging the Romi will reset the wireless configuration on the pi which could cause a mismatch with your Java code build configuration if you customized it.

**Comment by SammyPants37** [comment]
I can reach http://10.0.0.2/ and this is a fresh image (I made this issue just a little while after I imaged it)

**Comment by SammyPants37** [comment]
I just tested the romi reference code and that worked fine

**Comment by jpokornyiii** [comment]
Can you post a link to the robot code that doesn't work? I'll try it out as well.

**Comment by SammyPants37** [comment]
Yeah I can put it on GitHub at some point
________________________________

**Comment by jpokornyiii** [comment]
Can you check if you see "HALSimWS: WebSocket Connected" in the output as well? There were some changes between WPILib 2021 and WPILIB 2022 and the builld.gradle file. It may not be connecting at all.

**Comment by SammyPants37** [comment]
here is my code that isn't working
https://github.com/SammyPants37/romiWork-2022

**Comment by jpokornyiii** [comment]
I'll test this out when I get home tonight but my gut felling is that you are missing this in your build.gradle file:

wpi.sim.envVar("HALSIMWS_HOST", "10.0.0.2")
wpi.sim.addWebsocketsClient().defaultEnabled = true

This was coded differently in the past  and if you imported the project to FRC VS Code 2022 you would have to add them back.

**Comment by jpokornyiii** [comment]
Change above fixed it when I tested it out. Please confirm this fixes the issue.

**Comment by jpokornyiii** [comment]
Created above issue to follow up on the importing of romi projects to new VS Code versions. Will close this out. If this problem continues please create a new issue.
