### ISSUE TITLE
With WPILibPi 2023.1.1 Release the Romi Update firmware fails

### ISSUE THREAD

**Issue by mlazarew** [wpilibsuite/WPILibPi#229]
With [WPILibPi 2023.1.1 Release](https://github.com/wpilibsuite/WPILibPi/releases/tag/v2023.1.1) the Romi [Update firmware fails](https://www.chiefdelphi.com/t/update-firmware-fails/423650)

**Comment by PeterJohnson** [comment]
Yes, it's listed as a known issue on the release page.  I'm looking into it.

**Comment by PeterJohnson** [comment]
Fixed in 2023.2.1.
